//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int item_code { get; set; }
        public int min_qty { get; set; }
        public int current_qty { get; set; }
    
        public virtual Item_Master Item_Master { get; set; }
    }
}
