//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Item_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Master()
        {
            this.Purchase_Detail = new HashSet<Purchase_Detail>();
        }
    
        public int item_code { get; set; }
        [DisplayName("Item Name")]

        public string item_name { get; set; }
        [DisplayName("Unit")]

        public string item_unit { get; set; }
        [DisplayName("Rate")]

        public long item_rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Detail> Purchase_Detail { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
