//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Detail
    {
        public string purchase_no { get; set; }
        public int item_code { get; set; }
        public string item_name { get; set; }
        public int qty { get; set; }
        public long item_rate { get; set; }
        public long amount { get; set; }
        public int id { get; set; }
    
        public virtual Item_Master Item_Master { get; set; }
    }
}
