//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Services.Description;

    public partial class Vendor_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor_Master()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int vendor_code { get; set; }
        public string vendor_name { get; set; }
        public long vendor_contactno { get; set; }
        public string vendor_address { get; set; }
        public string vendor_state { get; set; }
        public string vendor_GSTno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
public enum State
{
    Gujarat,
    UP,
    MP,
    Bihar,
    Rajshthan,
    Maharashtra
}